// source: wozobject.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.wozobject.FullWozObjectReply', null, global);
goog.exportSymbol('proto.wozobject.UploadImageReply', null, global);
goog.exportSymbol('proto.wozobject.UploadImageRequest', null, global);
goog.exportSymbol('proto.wozobject.WozObjectImageReply', null, global);
goog.exportSymbol('proto.wozobject.WozObjectImageRequest', null, global);
goog.exportSymbol('proto.wozobject.WozObjectReply', null, global);
goog.exportSymbol('proto.wozobject.WozObjectRequestById', null, global);
goog.exportSymbol('proto.wozobject.WozObjectsReply', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.WozObjectRequestById = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.WozObjectRequestById, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.WozObjectRequestById.displayName = 'proto.wozobject.WozObjectRequestById';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.WozObjectsReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.wozobject.WozObjectsReply.repeatedFields_, null);
};
goog.inherits(proto.wozobject.WozObjectsReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.WozObjectsReply.displayName = 'proto.wozobject.WozObjectsReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.WozObjectReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.WozObjectReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.WozObjectReply.displayName = 'proto.wozobject.WozObjectReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.FullWozObjectReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.FullWozObjectReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.FullWozObjectReply.displayName = 'proto.wozobject.FullWozObjectReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.WozObjectImageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.WozObjectImageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.WozObjectImageRequest.displayName = 'proto.wozobject.WozObjectImageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.WozObjectImageReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.WozObjectImageReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.WozObjectImageReply.displayName = 'proto.wozobject.WozObjectImageReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.UploadImageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.UploadImageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.UploadImageRequest.displayName = 'proto.wozobject.UploadImageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.UploadImageReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.UploadImageReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.UploadImageReply.displayName = 'proto.wozobject.UploadImageReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.WozObjectRequestById.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.WozObjectRequestById.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.WozObjectRequestById} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectRequestById.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectnummer: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.WozObjectRequestById}
 */
proto.wozobject.WozObjectRequestById.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.WozObjectRequestById;
  return proto.wozobject.WozObjectRequestById.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.WozObjectRequestById} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.WozObjectRequestById}
 */
proto.wozobject.WozObjectRequestById.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWozobjectnummer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectRequestById.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.WozObjectRequestById.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.WozObjectRequestById} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectRequestById.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectnummer();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 wozobjectnummer = 1;
 * @return {number}
 */
proto.wozobject.WozObjectRequestById.prototype.getWozobjectnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.WozObjectRequestById} returns this
 */
proto.wozobject.WozObjectRequestById.prototype.setWozobjectnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.wozobject.WozObjectsReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.WozObjectsReply.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.WozObjectsReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.WozObjectsReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectsReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectsList: jspb.Message.toObjectList(msg.getWozobjectsList(),
    proto.wozobject.WozObjectReply.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.WozObjectsReply}
 */
proto.wozobject.WozObjectsReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.WozObjectsReply;
  return proto.wozobject.WozObjectsReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.WozObjectsReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.WozObjectsReply}
 */
proto.wozobject.WozObjectsReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.wozobject.WozObjectReply;
      reader.readMessage(value,proto.wozobject.WozObjectReply.deserializeBinaryFromReader);
      msg.addWozobjects(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectsReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.WozObjectsReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.WozObjectsReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectsReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.wozobject.WozObjectReply.serializeBinaryToWriter
    );
  }
};


/**
 * repeated WozObjectReply wozobjects = 1;
 * @return {!Array<!proto.wozobject.WozObjectReply>}
 */
proto.wozobject.WozObjectsReply.prototype.getWozobjectsList = function() {
  return /** @type{!Array<!proto.wozobject.WozObjectReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.wozobject.WozObjectReply, 1));
};


/**
 * @param {!Array<!proto.wozobject.WozObjectReply>} value
 * @return {!proto.wozobject.WozObjectsReply} returns this
*/
proto.wozobject.WozObjectsReply.prototype.setWozobjectsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.wozobject.WozObjectReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.wozobject.WozObjectReply}
 */
proto.wozobject.WozObjectsReply.prototype.addWozobjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.wozobject.WozObjectReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.wozobject.WozObjectsReply} returns this
 */
proto.wozobject.WozObjectsReply.prototype.clearWozobjectsList = function() {
  return this.setWozobjectsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.WozObjectReply.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.WozObjectReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.WozObjectReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectnummer: jspb.Message.getFieldWithDefault(msg, 1, 0),
    gemeentenaam: (f = msg.getGemeentenaam()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    straatnaam: (f = msg.getStraatnaam()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    huisnummer: jspb.Message.getFieldWithDefault(msg, 4, 0),
    huisletter: (f = msg.getHuisletter()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    huisnummertoevoeging: (f = msg.getHuisnummertoevoeging()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    postcode: (f = msg.getPostcode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    soortobjectcode: (f = msg.getSoortobjectcode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.WozObjectReply}
 */
proto.wozobject.WozObjectReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.WozObjectReply;
  return proto.wozobject.WozObjectReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.WozObjectReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.WozObjectReply}
 */
proto.wozobject.WozObjectReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWozobjectnummer(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setGemeentenaam(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setStraatnaam(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHuisnummer(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHuisletter(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHuisnummertoevoeging(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPostcode(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setSoortobjectcode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.WozObjectReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.WozObjectReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectnummer();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getGemeentenaam();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getStraatnaam();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHuisnummer();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getHuisletter();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHuisnummertoevoeging();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPostcode();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getSoortobjectcode();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 wozobjectnummer = 1;
 * @return {number}
 */
proto.wozobject.WozObjectReply.prototype.getWozobjectnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setWozobjectnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.StringValue gemeentenaam = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.WozObjectReply.prototype.getGemeentenaam = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.WozObjectReply} returns this
*/
proto.wozobject.WozObjectReply.prototype.setGemeentenaam = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.clearGemeentenaam = function() {
  return this.setGemeentenaam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.WozObjectReply.prototype.hasGemeentenaam = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue straatnaam = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.WozObjectReply.prototype.getStraatnaam = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.WozObjectReply} returns this
*/
proto.wozobject.WozObjectReply.prototype.setStraatnaam = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.clearStraatnaam = function() {
  return this.setStraatnaam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.WozObjectReply.prototype.hasStraatnaam = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 huisnummer = 4;
 * @return {number}
 */
proto.wozobject.WozObjectReply.prototype.getHuisnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setHuisnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional google.protobuf.StringValue huisletter = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.WozObjectReply.prototype.getHuisletter = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.WozObjectReply} returns this
*/
proto.wozobject.WozObjectReply.prototype.setHuisletter = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.clearHuisletter = function() {
  return this.setHuisletter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.WozObjectReply.prototype.hasHuisletter = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.StringValue huisnummertoevoeging = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.WozObjectReply.prototype.getHuisnummertoevoeging = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.WozObjectReply} returns this
*/
proto.wozobject.WozObjectReply.prototype.setHuisnummertoevoeging = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.clearHuisnummertoevoeging = function() {
  return this.setHuisnummertoevoeging(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.WozObjectReply.prototype.hasHuisnummertoevoeging = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.StringValue postcode = 7;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.WozObjectReply.prototype.getPostcode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 7));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.WozObjectReply} returns this
*/
proto.wozobject.WozObjectReply.prototype.setPostcode = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.clearPostcode = function() {
  return this.setPostcode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.WozObjectReply.prototype.hasPostcode = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.StringValue soortobjectcode = 8;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.WozObjectReply.prototype.getSoortobjectcode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 8));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.WozObjectReply} returns this
*/
proto.wozobject.WozObjectReply.prototype.setSoortobjectcode = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.clearSoortobjectcode = function() {
  return this.setSoortobjectcode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.WozObjectReply.prototype.hasSoortobjectcode = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.FullWozObjectReply.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.FullWozObjectReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.FullWozObjectReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.FullWozObjectReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectnummer: jspb.Message.getFieldWithDefault(msg, 1, 0),
    gemeentenaam: (f = msg.getGemeentenaam()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    straatnaam: (f = msg.getStraatnaam()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    huisnummer: jspb.Message.getFieldWithDefault(msg, 4, 0),
    huisletter: (f = msg.getHuisletter()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    huisnummertoevoeging: (f = msg.getHuisnummertoevoeging()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    postcode: (f = msg.getPostcode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    soortobjectcode: (f = msg.getSoortobjectcode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    wijkcode: (f = msg.getWijkcode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    buurtcode: (f = msg.getBuurtcode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    woonplaats: (f = msg.getWoonplaats()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    locatieomschrijving: (f = msg.getLocatieomschrijving()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    indicatieligging: (f = msg.getIndicatieligging()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    omschrijving: (f = msg.getOmschrijving()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.FullWozObjectReply}
 */
proto.wozobject.FullWozObjectReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.FullWozObjectReply;
  return proto.wozobject.FullWozObjectReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.FullWozObjectReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.FullWozObjectReply}
 */
proto.wozobject.FullWozObjectReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWozobjectnummer(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setGemeentenaam(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setStraatnaam(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHuisnummer(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHuisletter(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHuisnummertoevoeging(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPostcode(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setSoortobjectcode(value);
      break;
    case 9:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setWijkcode(value);
      break;
    case 10:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setBuurtcode(value);
      break;
    case 11:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setWoonplaats(value);
      break;
    case 12:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setLocatieomschrijving(value);
      break;
    case 13:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setIndicatieligging(value);
      break;
    case 14:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setOmschrijving(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.FullWozObjectReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.FullWozObjectReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.FullWozObjectReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.FullWozObjectReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectnummer();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getGemeentenaam();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getStraatnaam();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHuisnummer();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getHuisletter();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHuisnummertoevoeging();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPostcode();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getSoortobjectcode();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getWijkcode();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getBuurtcode();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getWoonplaats();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getLocatieomschrijving();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getIndicatieligging();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getOmschrijving();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 wozobjectnummer = 1;
 * @return {number}
 */
proto.wozobject.FullWozObjectReply.prototype.getWozobjectnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.setWozobjectnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.StringValue gemeentenaam = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getGemeentenaam = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setGemeentenaam = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearGemeentenaam = function() {
  return this.setGemeentenaam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasGemeentenaam = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue straatnaam = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getStraatnaam = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setStraatnaam = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearStraatnaam = function() {
  return this.setStraatnaam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasStraatnaam = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 huisnummer = 4;
 * @return {number}
 */
proto.wozobject.FullWozObjectReply.prototype.getHuisnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.setHuisnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional google.protobuf.StringValue huisletter = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getHuisletter = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setHuisletter = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearHuisletter = function() {
  return this.setHuisletter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasHuisletter = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.StringValue huisnummertoevoeging = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getHuisnummertoevoeging = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setHuisnummertoevoeging = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearHuisnummertoevoeging = function() {
  return this.setHuisnummertoevoeging(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasHuisnummertoevoeging = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.StringValue postcode = 7;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getPostcode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 7));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setPostcode = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearPostcode = function() {
  return this.setPostcode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasPostcode = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.StringValue soortobjectcode = 8;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getSoortobjectcode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 8));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setSoortobjectcode = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearSoortobjectcode = function() {
  return this.setSoortobjectcode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasSoortobjectcode = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.StringValue wijkcode = 9;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getWijkcode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 9));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setWijkcode = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearWijkcode = function() {
  return this.setWijkcode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasWijkcode = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.StringValue buurtcode = 10;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getBuurtcode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 10));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setBuurtcode = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearBuurtcode = function() {
  return this.setBuurtcode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasBuurtcode = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.StringValue woonplaats = 11;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getWoonplaats = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 11));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setWoonplaats = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearWoonplaats = function() {
  return this.setWoonplaats(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasWoonplaats = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.StringValue locatieomschrijving = 12;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getLocatieomschrijving = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 12));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setLocatieomschrijving = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearLocatieomschrijving = function() {
  return this.setLocatieomschrijving(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasLocatieomschrijving = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional google.protobuf.StringValue indicatieligging = 13;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getIndicatieligging = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 13));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setIndicatieligging = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearIndicatieligging = function() {
  return this.setIndicatieligging(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasIndicatieligging = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional google.protobuf.StringValue omschrijving = 14;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.wozobject.FullWozObjectReply.prototype.getOmschrijving = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 14));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.wozobject.FullWozObjectReply} returns this
*/
proto.wozobject.FullWozObjectReply.prototype.setOmschrijving = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wozobject.FullWozObjectReply} returns this
 */
proto.wozobject.FullWozObjectReply.prototype.clearOmschrijving = function() {
  return this.setOmschrijving(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wozobject.FullWozObjectReply.prototype.hasOmschrijving = function() {
  return jspb.Message.getField(this, 14) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.WozObjectImageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.WozObjectImageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.WozObjectImageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectImageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectnummer: jspb.Message.getFieldWithDefault(msg, 1, 0),
    onlyMain: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.WozObjectImageRequest}
 */
proto.wozobject.WozObjectImageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.WozObjectImageRequest;
  return proto.wozobject.WozObjectImageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.WozObjectImageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.WozObjectImageRequest}
 */
proto.wozobject.WozObjectImageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWozobjectnummer(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOnlyMain(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectImageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.WozObjectImageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.WozObjectImageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectImageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectnummer();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getOnlyMain();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional int64 wozobjectnummer = 1;
 * @return {number}
 */
proto.wozobject.WozObjectImageRequest.prototype.getWozobjectnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.WozObjectImageRequest} returns this
 */
proto.wozobject.WozObjectImageRequest.prototype.setWozobjectnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool only_main = 2;
 * @return {boolean}
 */
proto.wozobject.WozObjectImageRequest.prototype.getOnlyMain = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.wozobject.WozObjectImageRequest} returns this
 */
proto.wozobject.WozObjectImageRequest.prototype.setOnlyMain = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.WozObjectImageReply.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.WozObjectImageReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.WozObjectImageReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectImageReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    imageData: msg.getImageData_asB64(),
    isMain: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.WozObjectImageReply}
 */
proto.wozobject.WozObjectImageReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.WozObjectImageReply;
  return proto.wozobject.WozObjectImageReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.WozObjectImageReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.WozObjectImageReply}
 */
proto.wozobject.WozObjectImageReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setImageData(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsMain(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectImageReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.WozObjectImageReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.WozObjectImageReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectImageReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getImageData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getIsMain();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional bytes image_data = 1;
 * @return {!(string|Uint8Array)}
 */
proto.wozobject.WozObjectImageReply.prototype.getImageData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes image_data = 1;
 * This is a type-conversion wrapper around `getImageData()`
 * @return {string}
 */
proto.wozobject.WozObjectImageReply.prototype.getImageData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImageData()));
};


/**
 * optional bytes image_data = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImageData()`
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectImageReply.prototype.getImageData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImageData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.wozobject.WozObjectImageReply} returns this
 */
proto.wozobject.WozObjectImageReply.prototype.setImageData = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bool is_main = 2;
 * @return {boolean}
 */
proto.wozobject.WozObjectImageReply.prototype.getIsMain = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.wozobject.WozObjectImageReply} returns this
 */
proto.wozobject.WozObjectImageReply.prototype.setIsMain = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.UploadImageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.UploadImageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.UploadImageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.UploadImageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectnummer: jspb.Message.getFieldWithDefault(msg, 1, 0),
    imageData: msg.getImageData_asB64(),
    isMain: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.UploadImageRequest}
 */
proto.wozobject.UploadImageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.UploadImageRequest;
  return proto.wozobject.UploadImageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.UploadImageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.UploadImageRequest}
 */
proto.wozobject.UploadImageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWozobjectnummer(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setImageData(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsMain(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.UploadImageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.UploadImageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.UploadImageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.UploadImageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectnummer();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getImageData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getIsMain();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional int64 wozobjectnummer = 1;
 * @return {number}
 */
proto.wozobject.UploadImageRequest.prototype.getWozobjectnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.UploadImageRequest} returns this
 */
proto.wozobject.UploadImageRequest.prototype.setWozobjectnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes image_data = 2;
 * @return {!(string|Uint8Array)}
 */
proto.wozobject.UploadImageRequest.prototype.getImageData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes image_data = 2;
 * This is a type-conversion wrapper around `getImageData()`
 * @return {string}
 */
proto.wozobject.UploadImageRequest.prototype.getImageData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImageData()));
};


/**
 * optional bytes image_data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImageData()`
 * @return {!Uint8Array}
 */
proto.wozobject.UploadImageRequest.prototype.getImageData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImageData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.wozobject.UploadImageRequest} returns this
 */
proto.wozobject.UploadImageRequest.prototype.setImageData = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bool is_main = 3;
 * @return {boolean}
 */
proto.wozobject.UploadImageRequest.prototype.getIsMain = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.wozobject.UploadImageRequest} returns this
 */
proto.wozobject.UploadImageRequest.prototype.setIsMain = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.UploadImageReply.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.UploadImageReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.UploadImageReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.UploadImageReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    succes: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.UploadImageReply}
 */
proto.wozobject.UploadImageReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.UploadImageReply;
  return proto.wozobject.UploadImageReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.UploadImageReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.UploadImageReply}
 */
proto.wozobject.UploadImageReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSucces(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.UploadImageReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.UploadImageReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.UploadImageReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.UploadImageReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSucces();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool succes = 1;
 * @return {boolean}
 */
proto.wozobject.UploadImageReply.prototype.getSucces = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.wozobject.UploadImageReply} returns this
 */
proto.wozobject.UploadImageReply.prototype.setSucces = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


goog.object.extend(exports, proto.wozobject);
