// source: wozobject.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.wozobject.WozObjectReply', null, global);
goog.exportSymbol('proto.wozobject.WozObjectRequestById', null, global);
goog.exportSymbol('proto.wozobject.WozObjectsReply', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.WozObjectRequestById = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.WozObjectRequestById, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.WozObjectRequestById.displayName = 'proto.wozobject.WozObjectRequestById';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.WozObjectsReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.wozobject.WozObjectsReply.repeatedFields_, null);
};
goog.inherits(proto.wozobject.WozObjectsReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.WozObjectsReply.displayName = 'proto.wozobject.WozObjectsReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wozobject.WozObjectReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.wozobject.WozObjectReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wozobject.WozObjectReply.displayName = 'proto.wozobject.WozObjectReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.WozObjectRequestById.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.WozObjectRequestById.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.WozObjectRequestById} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectRequestById.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectnummer: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.WozObjectRequestById}
 */
proto.wozobject.WozObjectRequestById.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.WozObjectRequestById;
  return proto.wozobject.WozObjectRequestById.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.WozObjectRequestById} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.WozObjectRequestById}
 */
proto.wozobject.WozObjectRequestById.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWozobjectnummer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectRequestById.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.WozObjectRequestById.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.WozObjectRequestById} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectRequestById.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectnummer();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 wozobjectnummer = 1;
 * @return {number}
 */
proto.wozobject.WozObjectRequestById.prototype.getWozobjectnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.WozObjectRequestById} returns this
 */
proto.wozobject.WozObjectRequestById.prototype.setWozobjectnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.wozobject.WozObjectsReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.WozObjectsReply.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.WozObjectsReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.WozObjectsReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectsReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectsList: jspb.Message.toObjectList(msg.getWozobjectsList(),
    proto.wozobject.WozObjectReply.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.WozObjectsReply}
 */
proto.wozobject.WozObjectsReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.WozObjectsReply;
  return proto.wozobject.WozObjectsReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.WozObjectsReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.WozObjectsReply}
 */
proto.wozobject.WozObjectsReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.wozobject.WozObjectReply;
      reader.readMessage(value,proto.wozobject.WozObjectReply.deserializeBinaryFromReader);
      msg.addWozobjects(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectsReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.WozObjectsReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.WozObjectsReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectsReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.wozobject.WozObjectReply.serializeBinaryToWriter
    );
  }
};


/**
 * repeated WozObjectReply wozobjects = 1;
 * @return {!Array<!proto.wozobject.WozObjectReply>}
 */
proto.wozobject.WozObjectsReply.prototype.getWozobjectsList = function() {
  return /** @type{!Array<!proto.wozobject.WozObjectReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.wozobject.WozObjectReply, 1));
};


/**
 * @param {!Array<!proto.wozobject.WozObjectReply>} value
 * @return {!proto.wozobject.WozObjectsReply} returns this
*/
proto.wozobject.WozObjectsReply.prototype.setWozobjectsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.wozobject.WozObjectReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.wozobject.WozObjectReply}
 */
proto.wozobject.WozObjectsReply.prototype.addWozobjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.wozobject.WozObjectReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.wozobject.WozObjectsReply} returns this
 */
proto.wozobject.WozObjectsReply.prototype.clearWozobjectsList = function() {
  return this.setWozobjectsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wozobject.WozObjectReply.prototype.toObject = function(opt_includeInstance) {
  return proto.wozobject.WozObjectReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wozobject.WozObjectReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    wozobjectnummer: jspb.Message.getFieldWithDefault(msg, 1, 0),
    gemeentenaam: jspb.Message.getFieldWithDefault(msg, 2, ""),
    straatnaam: jspb.Message.getFieldWithDefault(msg, 3, ""),
    huisnummer: jspb.Message.getFieldWithDefault(msg, 4, 0),
    huisletter: jspb.Message.getFieldWithDefault(msg, 5, ""),
    huisnummertoevoeging: jspb.Message.getFieldWithDefault(msg, 6, ""),
    postcode: jspb.Message.getFieldWithDefault(msg, 7, ""),
    soortobjectcode: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wozobject.WozObjectReply}
 */
proto.wozobject.WozObjectReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wozobject.WozObjectReply;
  return proto.wozobject.WozObjectReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wozobject.WozObjectReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wozobject.WozObjectReply}
 */
proto.wozobject.WozObjectReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWozobjectnummer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGemeentenaam(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStraatnaam(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHuisnummer(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHuisletter(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setHuisnummertoevoeging(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPostcode(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSoortobjectcode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wozobject.WozObjectReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wozobject.WozObjectReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wozobject.WozObjectReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wozobject.WozObjectReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWozobjectnummer();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getGemeentenaam();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStraatnaam();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHuisnummer();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getHuisletter();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getHuisnummertoevoeging();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPostcode();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSoortobjectcode();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional int64 wozobjectnummer = 1;
 * @return {number}
 */
proto.wozobject.WozObjectReply.prototype.getWozobjectnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setWozobjectnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string gemeentenaam = 2;
 * @return {string}
 */
proto.wozobject.WozObjectReply.prototype.getGemeentenaam = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setGemeentenaam = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string straatnaam = 3;
 * @return {string}
 */
proto.wozobject.WozObjectReply.prototype.getStraatnaam = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setStraatnaam = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 huisnummer = 4;
 * @return {number}
 */
proto.wozobject.WozObjectReply.prototype.getHuisnummer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setHuisnummer = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string huisletter = 5;
 * @return {string}
 */
proto.wozobject.WozObjectReply.prototype.getHuisletter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setHuisletter = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string huisnummertoevoeging = 6;
 * @return {string}
 */
proto.wozobject.WozObjectReply.prototype.getHuisnummertoevoeging = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setHuisnummertoevoeging = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string postcode = 7;
 * @return {string}
 */
proto.wozobject.WozObjectReply.prototype.getPostcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setPostcode = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string soortobjectcode = 8;
 * @return {string}
 */
proto.wozobject.WozObjectReply.prototype.getSoortobjectcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.wozobject.WozObjectReply} returns this
 */
proto.wozobject.WozObjectReply.prototype.setSoortobjectcode = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


goog.object.extend(exports, proto.wozobject);
