export interface Straatnaam {
  id: string;
  gemeentecode: number;
  description: string;
}

export const straatnamen: Straatnaam[] = [
  { id: "'t Deel", gemeentecode: 1234, description: "'t Deel" },
  { id: "'t Fjouwerkant", gemeentecode: 1234, description: "'t Fjouwerkant" },
  { id: "'t Herntsje", gemeentecode: 1234, description: "'t Herntsje" },
  { id: "'t Hout", gemeentecode: 1234, description: "'t Hout" },
  { id: "'t Leger", gemeentecode: 1234, description: "'t Leger" },
  { id: "'t Lot", gemeentecode: 1234, description: "'t Lot" },
  { id: "'t Rak", gemeentecode: 1234, description: "'t Rak" },
  { id: "'t Stalt", gemeentecode: 1234, description: "'t Stalt" },
  { id: "'t Stap", gemeentecode: 1234, description: "'t Stap" },
  { id: "'t Suderhiem", gemeentecode: 1234, description: "'t Suderhiem" },
  { id: "'t Swin", gemeentecode: 1234, description: "'t Swin" },
  {
    id: 'Aafke van der Heideloane',
    gemeentecode: 1234,
    description: 'Aafke van der Heideloane'
  },
  { id: 'Aardappelland', gemeentecode: 1234, description: 'Aardappelland' },
  { id: 'Achterwei', gemeentecode: 1234, description: 'Achterwei' },
  { id: 'Akkerland', gemeentecode: 1234, description: 'Akkerland' },
  { id: 'Ald Daem', gemeentecode: 1234, description: 'Ald Daem' },
  { id: 'Alde Laweiswyk', gemeentecode: 1234, description: 'Alde Laweiswyk' },
  { id: 'Alde Wei', gemeentecode: 1234, description: 'Alde Wei' },
  { id: 'Aldegeasterdyk', gemeentecode: 1234, description: 'Aldegeasterdyk' },
  { id: 'Alferhof', gemeentecode: 1234, description: 'Alferhof' },
  { id: 'Ambachtsloane', gemeentecode: 1234, description: 'Ambachtsloane' },
  { id: 'Ame', gemeentecode: 1234, description: 'Ame' },
  { id: 'Amethist', gemeentecode: 1234, description: 'Amethist' },
  { id: 'AmpÃ¨relaan', gemeentecode: 1234, description: 'AmpÃ¨relaan' },
  { id: 'Anemoan', gemeentecode: 1234, description: 'Anemoan' },
  {
    id: 'Anske Aptekerstraat',
    gemeentecode: 1234,
    description: 'Anske Aptekerstraat'
  },
  { id: 'Appelhof', gemeentecode: 1234, description: 'Appelhof' },
  { id: 'Arendswyk', gemeentecode: 1234, description: 'Arendswyk' },
  { id: 'ArkepÃlle', gemeentecode: 1234, description: 'ArkepÃlle' },
  { id: 'BÃ»tendiken', gemeentecode: 1234, description: 'BÃ»tendiken' },
  { id: 'BÃ»tenom', gemeentecode: 1234, description: 'BÃ»tenom' },
  { id: 'BÃ»tewacht', gemeentecode: 1234, description: 'BÃ»tewacht' },
  { id: 'Baalder', gemeentecode: 1234, description: 'Baalder' },
  { id: 'Baansend', gemeentecode: 1234, description: 'Baansend' },
  { id: 'Bakboord', gemeentecode: 1234, description: 'Bakboord' },
  {
    id: 'Bearend Boardseswyk',
    gemeentecode: 1234,
    description: 'Bearend Boardseswyk'
  },
  { id: 'Berglaan', gemeentecode: 1234, description: 'Berglaan' },
  { id: 'Berkelaan', gemeentecode: 1234, description: 'Berkelaan' },
  { id: 'Beter Wonen', gemeentecode: 1234, description: 'Beter Wonen' },
  { id: 'Beugel', gemeentecode: 1234, description: 'Beugel' },
  { id: 'Biesland', gemeentecode: 1234, description: 'Biesland' },
  { id: 'Bikkelstenen', gemeentecode: 1234, description: 'Bikkelstenen' },
  { id: 'Bildreed', gemeentecode: 1234, description: 'Bildreed' },
  { id: 'Bildwei', gemeentecode: 1234, description: 'Bildwei' },
  { id: 'Binnendyks', gemeentecode: 1234, description: 'Binnendyks' },
  { id: 'Biskopswei', gemeentecode: 1234, description: 'Biskopswei' },
  { id: 'Blaauboerperk', gemeentecode: 1234, description: 'Blaauboerperk' },
  {
    id: 'Blauwverversregel',
    gemeentecode: 1234,
    description: 'Blauwverversregel'
  },
  { id: 'Bloemkamp', gemeentecode: 1234, description: 'Bloemkamp' },
  {
    id: 'Boarnburgumer Heawei',
    gemeentecode: 1234,
    description: 'Boarnburgumer Heawei'
  },
  { id: 'Boekweitkamp', gemeentecode: 1234, description: 'Boekweitkamp' },
  { id: 'Boelenswei', gemeentecode: 1234, description: 'Boelenswei' },
  { id: 'Boerekrookje', gemeentecode: 1234, description: 'Boerekrookje' },
  { id: 'Boerestreek', gemeentecode: 1234, description: 'Boerestreek' },
  { id: 'Boorn', gemeentecode: 1234, description: 'Boorn' },
  { id: 'Bosschawei', gemeentecode: 1234, description: 'Bosschawei' },
  { id: 'Bouburg', gemeentecode: 1234, description: 'Bouburg' },
  { id: 'Bouriciuslaan', gemeentecode: 1234, description: 'Bouriciuslaan' },
  { id: 'Bouwakker', gemeentecode: 1234, description: 'Bouwakker' },
  { id: 'Braambos', gemeentecode: 1234, description: 'Braambos' },
  { id: 'Broekfinne', gemeentecode: 1234, description: 'Broekfinne' },
  { id: 'BrouwersgrÃªft', gemeentecode: 1234, description: 'BrouwersgrÃªft' },
  { id: 'Brouwerssingel', gemeentecode: 1234, description: 'Brouwerssingel' },
  {
    id: 'Bruinsslotstraat',
    gemeentecode: 1234,
    description: 'Bruinsslotstraat'
  },
  { id: 'Buitenstvallaat', gemeentecode: 1234, description: 'Buitenstvallaat' },
  { id: 'Buorren', gemeentecode: 1234, description: 'Buorren' },
  { id: 'Burefen', gemeentecode: 1234, description: 'Burefen' },
  {
    id: 'Burgemeester Wuiteweg',
    gemeentecode: 1234,
    description: 'Burgemeester Wuiteweg'
  },
  { id: 'Burmanialaan', gemeentecode: 1234, description: 'Burmanialaan' },
  { id: 'Bysitterskamp', gemeentecode: 1234, description: 'Bysitterskamp' },
  {
    id: 'C Rienks de Boerstr',
    gemeentecode: 1234,
    description: 'C Rienks de Boerstr'
  },
  { id: 'Carneool', gemeentecode: 1234, description: 'Carneool' },
  { id: 'Claerkamp', gemeentecode: 1234, description: 'Claerkamp' },
  { id: 'Compagnonsplein', gemeentecode: 1234, description: 'Compagnonsplein' },
  { id: 'DÃºnoardswei', gemeentecode: 1234, description: 'DÃºnoardswei' },
  { id: 'De Akkers', gemeentecode: 1234, description: 'De Akkers' },
  { id: 'De Bank', gemeentecode: 1234, description: 'De Bank' },
  { id: 'De Barte', gemeentecode: 1234, description: 'De Barte' },
  { id: 'De Boeg', gemeentecode: 1234, description: 'De Boeg' },
  { id: 'De Bolder', gemeentecode: 1234, description: 'De Bolder' },
  { id: 'De Bolten', gemeentecode: 1234, description: 'De Bolten' },
  { id: 'De Boppeste', gemeentecode: 1234, description: 'De Boppeste' },
  { id: 'De Bosk', gemeentecode: 1234, description: 'De Bosk' },
  { id: 'De BrÃªge', gemeentecode: 1234, description: 'De BrÃªge' },
  { id: 'De Brekken', gemeentecode: 1234, description: 'De Brekken' },
  { id: 'De Dammen', gemeentecode: 1234, description: 'De Dammen' },
  { id: 'De Dobbe', gemeentecode: 1234, description: 'De Dobbe' },
  { id: 'De Doese', gemeentecode: 1234, description: 'De Doese' },
  { id: 'De Draai', gemeentecode: 1234, description: 'De Draai' },
  { id: 'De Dracht', gemeentecode: 1234, description: 'De Dracht' },
  { id: 'De Drift', gemeentecode: 1234, description: 'De Drift' },
  { id: 'De Ee', gemeentecode: 1234, description: 'De Ee' },
  { id: 'De Emma', gemeentecode: 1234, description: 'De Emma' },
  { id: 'De Excelsior', gemeentecode: 1234, description: 'De Excelsior' },
  { id: 'De Feart', gemeentecode: 1234, description: 'De Feart' },
  { id: 'De Fintsjes', gemeentecode: 1234, description: 'De Fintsjes' },
  { id: 'De Flearbosk', gemeentecode: 1234, description: 'De Flearbosk' },
  { id: 'De Foreest', gemeentecode: 1234, description: 'De Foreest' },
  { id: 'De Foute', gemeentecode: 1234, description: 'De Foute' },
  { id: 'De Frisia', gemeentecode: 1234, description: 'De Frisia' },
  { id: 'De Friso', gemeentecode: 1234, description: 'De Friso' },
  { id: 'De Gagelpol', gemeentecode: 1234, description: 'De Gagelpol' },
  { id: 'De Geasten', gemeentecode: 1234, description: 'De Geasten' },
  { id: 'De Geeuw', gemeentecode: 1234, description: 'De Geeuw' },
  { id: 'De Giek', gemeentecode: 1234, description: 'De Giek' },
  { id: 'De Goudberch', gemeentecode: 1234, description: 'De Goudberch' },
  { id: 'De Graft', gemeentecode: 1234, description: 'De Graft' },
  { id: 'De Greide', gemeentecode: 1234, description: 'De Greide' },
  { id: 'De Groene zoom', gemeentecode: 1234, description: 'De Groene zoom' },
  { id: 'De Hage', gemeentecode: 1234, description: 'De Hage' },
  { id: 'De Heide', gemeentecode: 1234, description: 'De Heide' },
  { id: 'De Hemmen', gemeentecode: 1234, description: 'De Hemmen' },
  { id: 'De Hoarnen', gemeentecode: 1234, description: 'De Hoarnen' },
  { id: 'De Hoge Bomen', gemeentecode: 1234, description: 'De Hoge Bomen' },
  { id: 'De Houtkamp', gemeentecode: 1234, description: 'De Houtkamp' },
  { id: 'De Hoven', gemeentecode: 1234, description: 'De Hoven' },
  { id: 'De Jerden', gemeentecode: 1234, description: 'De Jerden' },
  { id: 'De Kamp', gemeentecode: 1234, description: 'De Kamp' },
  { id: 'De Kamperfoelie', gemeentecode: 1234, description: 'De Kamperfoelie' },
  { id: 'De Klim', gemeentecode: 1234, description: 'De Klim' },
  { id: 'De Klynhoeke', gemeentecode: 1234, description: 'De Klynhoeke' },
  { id: 'De Knobben', gemeentecode: 1234, description: 'De Knobben' },
  { id: 'De Koai', gemeentecode: 1234, description: 'De Koai' },
  { id: 'De Kolken', gemeentecode: 1234, description: 'De Kolken' },
  { id: 'De Kromte', gemeentecode: 1234, description: 'De Kromte' },
  { id: 'De Landerijen', gemeentecode: 1234, description: 'De Landerijen' },
  { id: 'De Lanen', gemeentecode: 1234, description: 'De Lanen' },
  { id: 'De Lange West', gemeentecode: 1234, description: 'De Lange West' },
  { id: 'De Lege Ein', gemeentecode: 1234, description: 'De Lege Ein' },
  { id: 'De Leijen', gemeentecode: 1234, description: 'De Leijen' },
  { id: 'De Lijkant', gemeentecode: 1234, description: 'De Lijkant' },
  { id: 'De Linebeammen', gemeentecode: 1234, description: 'De Linebeammen' },
  { id: 'De Lits', gemeentecode: 1234, description: 'De Lits' },
  { id: 'De Marke', gemeentecode: 1234, description: 'De Marke' },
  { id: 'De Meent', gemeentecode: 1234, description: 'De Meent' },
  { id: 'De Meer', gemeentecode: 1234, description: 'De Meer' },
  { id: 'De Middelgeast', gemeentecode: 1234, description: 'De Middelgeast' },
  { id: 'De Nijverheid', gemeentecode: 1234, description: 'De Nijverheid' },
  { id: 'De Nova Cura', gemeentecode: 1234, description: 'De Nova Cura' },
  { id: 'De Oppers', gemeentecode: 1234, description: 'De Oppers' },
  { id: 'De Orion', gemeentecode: 1234, description: 'De Orion' },
  { id: 'De Parken', gemeentecode: 1234, description: 'De Parken' },
  {
    id: 'De Peinder Mieden',
    gemeentecode: 1234,
    description: 'De Peinder Mieden'
  },
  { id: 'De Petten', gemeentecode: 1234, description: 'De Petten' },
  { id: 'De Pikstiennen', gemeentecode: 1234, description: 'De Pikstiennen' },
  { id: 'De Posten', gemeentecode: 1234, description: 'De Posten' },
  { id: 'De Ried', gemeentecode: 1234, description: 'De Ried' },
  { id: 'De Rien', gemeentecode: 1234, description: 'De Rien' },
  { id: 'De Ring', gemeentecode: 1234, description: 'De Ring' },
  { id: 'De Rival', gemeentecode: 1234, description: 'De Rival' },
  { id: 'De Roef', gemeentecode: 1234, description: 'De Roef' },
  { id: 'De Rozetuin', gemeentecode: 1234, description: 'De Rozetuin' },
  { id: 'De Scheiding', gemeentecode: 1234, description: 'De Scheiding' },
  { id: 'De Singel', gemeentecode: 1234, description: 'De Singel' },
  { id: 'De Sipen', gemeentecode: 1234, description: 'De Sipen' },
  { id: 'De Skieding', gemeentecode: 1234, description: 'De Skieding' },
  { id: 'De Slag', gemeentecode: 1234, description: 'De Slag' },
  { id: 'De Steven', gemeentecode: 1234, description: 'De Steven' },
  { id: 'De Stoeken', gemeentecode: 1234, description: 'De Stoeken' },
  { id: 'De Stok', gemeentecode: 1234, description: 'De Stok' },
  { id: 'De Tijen', gemeentecode: 1234, description: 'De Tijen' },
  { id: 'De Tille', gemeentecode: 1234, description: 'De Tille' },
  { id: 'De Trisken', gemeentecode: 1234, description: 'De Trisken' },
  { id: 'De Tsjollen', gemeentecode: 1234, description: 'De Tsjollen' },
  { id: 'De Tuinen', gemeentecode: 1234, description: 'De Tuinen' },
  {
    id: 'De Twee Gebroeders',
    gemeentecode: 1234,
    description: 'De Twee Gebroeders'
  },
  { id: 'De Tynje', gemeentecode: 1234, description: 'De Tynje' },
  {
    id: 'De Veertien Roeden',
    gemeentecode: 1234,
    description: 'De Veertien Roeden'
  },
  { id: 'De Velden', gemeentecode: 1234, description: 'De Velden' },
  { id: 'De Vogelweide', gemeentecode: 1234, description: 'De Vogelweide' },
  { id: 'De Vore', gemeentecode: 1234, description: 'De Vore' },
  { id: 'De Warande', gemeentecode: 1234, description: 'De Warande' },
  { id: 'De Warrebosk', gemeentecode: 1234, description: 'De Warrebosk' },
  { id: 'De Warren', gemeentecode: 1234, description: 'De Warren' },
  { id: 'De Wear', gemeentecode: 1234, description: 'De Wear' },
  { id: 'De Weeme', gemeentecode: 1234, description: 'De Weeme' },
  { id: 'De Werf', gemeentecode: 1234, description: 'De Werf' },
  { id: 'De Wetering', gemeentecode: 1234, description: 'De Wetering' },
  { id: 'De Wetterwille', gemeentecode: 1234, description: 'De Wetterwille' },
  { id: 'De Wiel', gemeentecode: 1234, description: 'De Wiel' },
  { id: 'De Wier', gemeentecode: 1234, description: 'De Wier' },
  { id: 'De Wijnakker', gemeentecode: 1234, description: 'De Wijnakker' },
  { id: 'De Wilgepol', gemeentecode: 1234, description: 'De Wilgepol' },
  { id: 'De Zanding', gemeentecode: 1234, description: 'De Zanding' },
  { id: 'De Zool', gemeentecode: 1234, description: 'De Zool' },
  { id: 'De Zwaai', gemeentecode: 1234, description: 'De Zwaai' },
  { id: 'De Zwaden', gemeentecode: 1234, description: 'De Zwaden' },
  { id: 'De Zwaluwstaart', gemeentecode: 1234, description: 'De Zwaluwstaart' },
  {
    id: 'Dokter Siebingasingel',
    gemeentecode: 1234,
    description: 'Dokter Siebingasingel'
  },
  { id: 'Doktersheide', gemeentecode: 1234, description: 'Doktersheide' },
  { id: 'Dollard', gemeentecode: 1234, description: 'Dollard' },
  { id: 'Donia', gemeentecode: 1234, description: 'Donia' },
  { id: 'Dopheide', gemeentecode: 1234, description: 'Dopheide' },
  { id: 'Dorsvloer', gemeentecode: 1234, description: 'Dorsvloer' },
  { id: 'Douwstraweg', gemeentecode: 1234, description: 'Douwstraweg' },
  {
    id: 'Drachtster Heawei',
    gemeentecode: 1234,
    description: 'Drachtster Heawei'
  },
  {
    id: 'Ds Carsjenssingel',
    gemeentecode: 1234,
    description: 'Ds Carsjenssingel'
  },
  {
    id: 'Ds. van Apeldoornwei',
    gemeentecode: 1234,
    description: 'Ds. van Apeldoornwei'
  },
  { id: 'Ds. Visscherwei', gemeentecode: 1234, description: 'Ds. Visscherwei' },
  { id: 'Duizendblad', gemeentecode: 1234, description: 'Duizendblad' }
];
